import { Poll, Moment, User } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'user_001',
    name: 'Alex Chen',
    username: 'alexc',
    avatarUrl: '/avatars/alex.png',
    campus: 'State University',
    year: 'Sophomore',
    points: 1250,
    beastTokens: 15,
    createdAt: new Date('2024-09-01'),
  },
  {
    id: 'user_002',
    name: 'Jordan Lee',
    username: 'jordanl',
    avatarUrl: '/avatars/jordan.png',
    campus: 'State University',
    year: 'Junior',
    points: 2100,
    beastTokens: 8,
    createdAt: new Date('2024-08-15'),
  },
  {
    id: 'user_003',
    name: 'Taylor Kim',
    username: 'taylork',
    avatarUrl: '/avatars/taylor.png',
    campus: 'State University',
    year: 'Freshman',
    points: 890,
    beastTokens: 22,
    createdAt: new Date('2024-09-10'),
  },
];

export const MOCK_POLLS: Poll[] = [
  {
    id: 'poll_001',
    question: 'Which finalist should get the Beast Boost wildcard?',
    options: [
      { id: 'opt_1', text: 'Clip #7 (Comedy Gold)', votesCount: 234, percentage: 42 },
      { id: 'opt_2', text: 'Clip #12 (Underdog)', votesCount: 156, percentage: 28 },
      { id: 'opt_3', text: 'Clip #19 (Epic Fail)', votesCount: 112, percentage: 20 },
      { id: 'opt_4', text: 'Clip #3 (Dark Horse)', votesCount: 56, percentage: 10 },
    ],
    category: 'beast',
    beastLinkage: 'wildcard',
    beastWeekId: 'beast_week_007',
    totalVotes: 558,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'poll_002',
    question: 'What should next week\'s Beast challenge be?',
    options: [
      { id: 'opt_5', text: 'Campus Parkour Run', votesCount: 445, percentage: 38 },
      { id: 'opt_6', text: 'Talent Showdown', votesCount: 378, percentage: 32 },
      { id: 'opt_7', text: 'Cooking Challenge', votesCount: 234, percentage: 20 },
      { id: 'opt_8', text: 'Dance Battle', votesCount: 118, percentage: 10 },
    ],
    category: 'beast',
    beastLinkage: 'next_theme',
    beastWeekId: 'beast_week_007',
    totalVotes: 1175,
    expiresAt: new Date(Date.now() + 48 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'poll_003',
    question: 'Best spot on campus for coffee?',
    options: [
      { id: 'opt_9', text: 'The Daily Grind', votesCount: 312, percentage: 45 },
      { id: 'opt_10', text: 'Library Café', votesCount: 243, percentage: 35 },
      { id: 'opt_11', text: 'Student Union', votesCount: 89, percentage: 13 },
      { id: 'opt_12', text: 'Off-Campus Starbucks', votesCount: 48, percentage: 7 },
    ],
    category: 'campus',
    totalVotes: 692,
    expiresAt: new Date(Date.now() + 12 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
];

export const MOCK_MOMENTS: Moment[] = [
  {
    id: 'moment_001',
    userId: 'user_002',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=1000&fit=crop',
    caption: 'Practicing for this week\'s Beast challenge 🎬😂',
    isBeastMoment: true,
    beastWeekId: 'beast_week_007',
    allowInBeastReel: true,
    reactionsCount: 47,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    expiresAt: new Date(Date.now() + 21 * 60 * 60 * 1000),
    user: MOCK_USERS[1],
  },
  {
    id: 'moment_002',
    userId: 'user_003',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=1000&fit=crop',
    caption: 'Study group vibes before finals 📚✨',
    isBeastMoment: false,
    allowInBeastReel: false,
    reactionsCount: 23,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    expiresAt: new Date(Date.now() + 23 * 60 * 60 * 1000),
    user: MOCK_USERS[2],
  },
  {
    id: 'moment_003',
    userId: 'user_001',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    caption: 'Behind the scenes: my Beast submission prep 🎥',
    isBeastMoment: true,
    beastWeekId: 'beast_week_007',
    allowInBeastReel: true,
    reactionsCount: 89,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    expiresAt: new Date(Date.now() + 19 * 60 * 60 * 1000),
    user: MOCK_USERS[0],
  },
  {
    id: 'moment_004',
    userId: 'user_002',
    imageUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&h=1000&fit=crop',
    caption: 'Game day energy! Let\'s go! 🏈',
    isBeastMoment: false,
    allowInBeastReel: false,
    reactionsCount: 34,
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000),
    expiresAt: new Date(Date.now() + 17 * 60 * 60 * 1000),
    user: MOCK_USERS[1],
  },
];
